spring.application.name=employee-service
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/employee_ms_db
spring.datasource.username=root
spring.datasource.password=MySQL@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

#Retry config
resilience4j.retry.instances.authService.max-attempts=3
resilience4j.retry.instances.authService.wait-duration=2s
resilience4j.retry.instances.authService.retry-exceptions=feign.RetryableException

# Circuit Breaker config
resilience4j.circuitbreaker.instances.authService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.authService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.authService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.authService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.authService.record-exceptions=feign.RetryableException